spring.application.username=backend
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=userDB
spring.data.mongodb.auto-index-creation=true
govt.api.url=/resource/3b01bcb8-0b14-4abf-b6f2-c1bfd384ba69
govt.api.key=579b464db66ec23bdd000001cdc3b564546246a772a26393094f5645
