spring.application.username=backend
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=userDB
spring.data.mongodb.auto-index-creation=true
govt.api.url=/resource/3b01bcb8-0b14-4abf-b6f2-c1bfd384ba69
govt.api.key=579b464db66ec23bdd000001cdc3b564546246a772a26393094f5645
spring.redis.host=localhost
spring.redis.port=6379
spring.cache.type=redis
spring.cache.redis.time-to-live=3600000
mailgun.api.key=54c4b224dc5885035c0eef73d1312c8d-c6620443-3a38dbd7
mailgun.domain=sandbox86666a5386d04d0ebc9266b2325d658a.mailgun.org
mailgun.from=Email Verify <verify@sandbox86666a5386d04d0ebc9266b2325d658a.mailgun.org>
