spring.application.username=backend

# MongoDB Configuration
spring.data.mongodb.host=${SPRING_DATA_MONGODB_HOST:localhost}
spring.data.mongodb.port=${SPRING_DATA_MONGODB_PORT:27017}
spring.data.mongodb.database=${SPRING_DATA_MONGODB_DATABASE:userDB}
spring.data.mongodb.auto-index-creation=true

# Indian Government API Configuration
govt.api.url=/resource/3b01bcb8-0b14-4abf-b6f2-c1bfd384ba69
govt.api.key=${GOVT_API_KEY:579b464db66ec23bdd000001cdc3b564546246a772a26393094f5645}

# Redis Cache Configuration
spring.redis.host=${SPRING_REDIS_HOST:localhost}
spring.redis.port=${SPRING_REDIS_PORT:6379}
spring.cache.type=redis
spring.cache.redis.time-to-live=3600000

# Mailgun Email Verification
mailgun.api.key=${MAILGUN_API_KEY:54c4b224dc5885035c0eef73d1312c8d-c6620443-3a38dbd7}
mailgun.domain=${MAILGUN_DOMAIN:sandbox86666a5386d04d0ebc9266b2325d658a.mailgun.org}
mailgun.from=${MAILGUN_FROM:Email Verify <verify@sandbox86666a5386d04d0ebc9266b2325d658a.mailgun.org>}
