version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aqi_app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - GOVT_API_KEY=579b464db66ec23bdd000001cdc3b564546246a772a26393094f5645
    depends_on:
      - mongodb
      - redis
    restart: always

  mongodb:
    image: mongo:latest
    container_name: aqi_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  redis:
    image: redis:alpine
    container_name: aqi_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  mongo_data:
  redis_data:
